### ISSUE TITLE
GitPitchのskyテーマにあたっているスタイルを確認する

### ISSUE THREAD

**Issue by ftnext** [ftnext/2020_slides#24]
https://github.com/ftnext/2020_slides/blob/master/pyconhiro_Oct_connect_global/PITCHME.yaml によるスタイル指定がCSSにどう反映されているかを確認していく

**Comment by ftnext** [comment]
## フォント

```yaml
theme-headline : [ "Ubuntu", "#1C1C1C", "none", "#1C1C1C", "100", "120", "15" ]
theme-byline   : [ "Ubuntu", "#1C1C1C", "none", "#1C1C1C", "100", "110", "15" ]
theme-text     : [ "Ubuntu", "#1C1C1C", "none", "#1C1C1C", "100", "100", "15" ]
```

PITCHME.yaml で `theme-{headline,byline,text}`にしていた`Ubuntu`はfont familyだった
ref: https://gitpitch.github.io/gitpitch/#/theme/template?id=headline-setting
source: https://github.com/gitpitch/gitpitch/blob/master/docs/theme/template.md#headline-setting

Google Fontsから利用できる
https://fonts.google.com/specimen/Ubuntu

CSSでの指定の仕方
https://developers.google.com/fonts/docs/css2#individual_styles_such_as_weight
`@import url('https://fonts.googleapis.com/css2?family=Ubuntu:wght@500;700&display=swap');`

- h1とh2 (headline) には `font-weight: 700;`
- h3とh4 (byline) には `font-weight: 500;`

で適用する（→これで文字が太くなる）

theme-text（地の文）にもUbuntuを適用する（アルファベットに反映される）
GitPitchと見比べてweight 400を設定した
